config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  get 'cart/index'

  constraints(SubdomainPresent) do
    devise_for :users
    resources :products
    resources :clients
    resources :orders
    resources :attendances
    resources :clients
    resources :searches

    root 'products#index', as: :subdomain_root
    get 'choose', to: 'orders#choose_products'
    get 'clear', to: 'cart#clear'
    get 'add/:id/:page', to: 'cart#add', as: 'add'
    get 'remove/:id', to: 'cart#remove', as: 'remove'
    get 'cart/index', to: 'cart#index', as: 'cart'
  end

  constraints(SubdomainBlank) do
    root 'pages#home'
    resources :accounts, only: [:new, :create]
    get 'pages/home' => 'pages#home'
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  
  def add
    id = params[:id]
    
    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
    
    if cart[id] then
      cart[id] = cart[id] + 1
    else
      cart[id] = 1
    end
    
    redirect_to products_path(:page => params[:page])
  end
  
  def remove
    id = params[:id]
    
    
    cart = session[:cart]
    
    
    if cart[id] then
      cart.delete("#{id}")
    end
    
    redirect_to cart_path
  end
  
  def clear
    session[:cart] = nil
    redirect_to '#'
  end
  
  def index
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
    
  end
  
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<h1>Produtos Adicionados</h1>

<% if session[:cart] %>
	<%= link_to "Esvaziar Carrinho", clear_path %>
<% end %>
<ul>
<% @cart.each do |id, quantity| %>
	<% product = Product.find(id) %>
	
	<li>
		<p>Marca: <%= product.brand %></p>
		<p>Tipo: <%= product.product_type %></p>
		<p>Quantidade: <%= quantity %></p>
		<p>Preço: <%= number_to_currency(product.price, :unit => 'R$') %></p>
		<p><%= link_to "Remover da Venda", remove_path(product) %></p>
	</li>
<% end %>
</ul>