config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  get 'cart/index'

  constraints(SubdomainPresent) do
    devise_for :users
    resources :products
    resources :clients
    resources :orders
    resources :attendances
    resources :clients
    resources :searches

    root 'products#index', as: :subdomain_root
    get 'choose', to: 'orders#choose_products'
    get 'clear', to: 'cart#clear'
    get 'add/:id/:page', to: 'cart#add', as: 'add'
    get 'remove/:id', to: 'cart#remove', as: 'remove'
    get 'cart/index', to: 'cart#index', as: 'cart'
  end

  constraints(SubdomainBlank) do
    root 'pages#home'
    resources :accounts, only: [:new, :create]
    get 'pages/home' => 'pages#home'
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  #self.inheritance_column = nil #nao tenho certeza disso aqui, vi no stackoverflow
  #has_many :atendances
  #has_many :users, through: :attendances
  has_many :orders
  has_many :products, through: :orders
  has_many :users, through: :orders
  
	#belongs_to :account
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        puts "deu erro"
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :age, :cpf, :rg, :p, :rate)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<div class="col-md-8 col-md-offset-2">
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.label :name, "Nome do Cliente:" %>
      <%= f.input :name, label: false %>
    </div>

    <div class="form-inline">
      <div class="form-group">
      <%= f.label :age, "Idade:" %>
      <%= f.input :age, label: false %>
      </div>
    
      <div class="form-group">
      <%= f.label :cpf, "CPF:" %>
      <%= f.input :cpf, label: false %>
      </div>
  
      <div class="form-group">
      <%= f.label :rg, "RG:" %>
      <%= f.input :rg, label: false %>
      </div>
    
    </div>

    <div class="form-group">
      <%= f.label :adress, "Endereço do Cliente:" %>
      <%= f.input :adress, label: false %>
    </div>

    <div class="form-group">
      <%= f.input :rate %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary pull-right" %>
  </div>
  <%= link_to 'Voltar', clients_path, class: "btn btn-primary pull-left" %>
<% end %>
</div>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @client %> |
<%= link_to 'Voltar', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Seus Clientes</h1>

<h4>Se o cliente estiver cadastrado clique em <strong>Escolher</strong> para continuar com a venda. Ou então cadastre um novo cliente.</h4>

<table class="table table-hover table-bordered text-center">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>CPF</th>
      <th>RG</th>
      <th>Endereço</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.age %></td>
        <td><%= client.cpf %></td>
        <td><%= client.rg %></td>
        <td><%= client.adress %></td>
        <td><%= client.rate %></td>
        <td><%= link_to 'Escolher', client, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Editar', edit_client_path(client), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Apagar', client, class: 'btn btn-danger', method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Novo Cliente', new_client_path, class: 'btn btn-primary pull-right' %>
<%= link_to 'Voltar', products_path, class: 'btn btn-primary pull-left' %>

app/views/clients/new.html.erb
<h1 class="text-center">Cadastrar Cliente</h1>

<%= render 'form' %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading"><h1 class="text-center">Detalhes do Cliente</h1></div> 
  <h4 class="text-center">Confira os dados do cliente antes de prosseguir com a venda</h4> 
    <div class="panel-body">  
      <p>
        <strong>Nome:</strong>
        <%= @client.name %>
      </p>

      <p>
        <strong>Idade:</strong>
        <%= @client.age %>
      </p>

      <p>
        <strong>CPF:</strong>
        <%= @client.cpf %>
      </p>

      <p>
        <strong>RG:</strong>
        <%= @client.rg %>
      </p>

      <p>
        <strong>Endereço:</strong>
        <%= @client.adress %>
      </p>

      <p>
        <strong>Rate:</strong>
        <%= @client.rate %>
      </p>

      <p>
      <%= link_to 'Editar', edit_client_path(@client) %> |
      <%= link_to 'Voltar', clients_path %>
      </p>
      <%= link_to 'Seguir Para Venda', new_order_path(:client => @client.id), class: 'btn btn-primary' %>
    </div>
  </div>
</div>