config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  get 'cart/index'

  constraints(SubdomainPresent) do
    devise_for :users
    resources :products
    resources :clients
    resources :orders
    resources :attendances
    resources :clients
    resources :searches

    root 'products#index', as: :subdomain_root
    get 'choose', to: 'orders#choose_products'
    get 'clear', to: 'cart#clear'
    get 'add/:id/:page', to: 'cart#add', as: 'add'
    get 'remove/:id', to: 'cart#remove', as: 'remove'
    get 'cart/index', to: 'cart#index', as: 'cart'
  end

  constraints(SubdomainBlank) do
    root 'pages#home'
    resources :accounts, only: [:new, :create]
    get 'pages/home' => 'pages#home'
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	#self.inheritance_column = nil #nao tenho certeza disso aqui, vi no stackoverflow
	#belongs_to :account
  has_many :orders
  has_many :clients, through: :orders
  has_many :users, through: :orders
  #has_many :attendance, through: :orders
  
  #Definindo os scopes.
  #Cada scope pode ser chamado como um método no controller
  scope :gender, -> (gender) { where("gender like ?", "#{gender}%") }
  scope :product_type, -> (product_type) { where("product_type like ?", "#{product_type}%") }
  scope :brand, -> (brand) { where("brand like ?", "#{brand}%")}
  scope :price_max, -> (price_max) { where("price <= ?", "#{price_max}")}
  scope :price_min, -> (price_min) { where("price >= ?", "#{price_min}")}
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(nil) # cria um scope anônimo (todos os produtos)
    @products = Product.paginate(:page => params[:page], :per_page => 5)
    @products = @products.gender(params[:gender]) if params[:gender].present?
    @products = @products.brand(params[:brand]) if params[:brand].present?
    @products = @products.product_type(params[:product_type]) if params[:product_type].present?
    @products = @products.price_max(params[:price_max]) if params[:price_max].present?
    @products = @products.price_min(params[:price_min]) if params[:price_min].present?
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
    
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:brand, :size, :reference, :gender, :product_type, :price, :cost_price, :stock_quantity)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="col-md-8 col-md-offset-2">
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.label :reference, "Referência" %>
    <%= f.input :reference, label: false %>

    <%= f.label :brand, "Marca" %>
    <%= f.input :brand, label: false %>

    <%= f.label :size, "Tamanho" %>
    <%= f.input :size, label: false %>

    <div class="input-group">
      <%= f.label :gender, "Gênero:" %>
      <%= f.select :gender, options_for_select(['Masculino', 'Feminino']), label: false %>
    </div>
    <br>
    <div class="input-group">
      <%= f.label :product_type, "Tipo:" %>
      <%= f.select :product_type, options_for_select(['Receituário', 'Esportivo']), label: false %>
    </div>
    <br>

    <%= f.label :cost_price, "Preço de Custo (R$)" %>
    <%= f.input :cost_price, class: 'form-control', label: false %>
    

    <%= f.label :price, "Preço de Venda (R$)" %>
    <%= f.input :price, label: false %>

    <%= f.label :stock_quantity, "Quantidade em Estoque" %>
    <%= f.input :stock_quantity, label: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %><br><br>
  </div>
  <div>
    <%= link_to 'Voltar', products_path, class: "btn btn-primary btn-sm" %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if @products.present? %>
<div class="panel panel-default">
<div class="panel-heading"><h1 class="text-center">Estoque</h1>
</div>

<div class="panel-body">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <h3>Filtro</h3>
    <div></div>
    <%= form_tag(products_path, :method =>'get', id: "search-form", class: "navbar-form navbar-left") do %>


    <div class="form-group">
      <%= text_field_tag :brand, params[:brand], placeholder: "digite a marca", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= text_field_tag :gender, params[:gender], placeholder: "digite o gênero", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= text_field_tag :product_type, params[:product_type], placeholder: "digite o tipo", class: "form-control" %>
    </div>

    <div class="form-group">
      De R$: <%= text_field_tag :price_min, params[:price_min], placeholder: "digite o preço mínimo", class: "form-control" %> a 
    
      R$: <%= text_field_tag :price_max, params[:price_max], placeholder: "digite o preço máximo", class: "form-control" %>
    </div>

      <span class="form-group-btn">
      <br><br><%= submit_tag "Filtar", class: 'btn btn-primary' %>
    </span>
    
    <% end %>
  </div>
</nav>

</div>

<div>
<table class="table table-hover table-bordered text-center">
  <% if user_signed_in? %>
    <div class="text-center">
      <p>
        Escolha um produto do estoque e clique em <strong>ADICIONAR A VENDA</strong> em seguida clique em <strong>PROSSEGUIR COM A VENDA</strong>. 
        Ou então adicione um novo produto.
      </p>
    </div>
    <div>
      <%= link_to 'Adicionar Novo Produto', new_product_path, class: "btn btn-primary btn-sm pull-left" %>
      
      <%= link_to "Prosseguir com a Venda", clients_path, class: 'btn btn-primary btn-sm pull-right' %>
        
      <br><br>
    </div>
  
  <% end %>

	<thead>
	  <tr>
	  	<th class="text-center">Referência</th>
	    <th class="text-center">Marca</th>
	    <th class="text-center">Tamanho</th>
	    <th class="text-center">Gênero</th>
	    <th class="text-center">Tipo</th>
      <th class="text-center">Preço de Custo</th>
	    <th class="text-center">Preço de Venda</th>
      <th class="text-center">Quantidade em Estoque</th>
	    <th lass="text-center"></th>
		<th class="text-center"></th>
		<th class="text-center">Quantidade Adicionada a Venda</th>
	  </tr>
    </thead>
 <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.reference %></td>
      <td><%= product.brand %></td>
      <td><%= product.size %></td>
      <td><%= product.gender %></td>
      <td><%= product.product_type %></td>
      <td><%= number_to_currency(product.cost_price, :unit => 'R$') %></td>
      <td><%= number_to_currency(product.price, :unit => 'R$') %></td>
      <td><%= product.stock_quantity %></td>
      <td><p class="btn btn-default"><%= link_to "Ver Detalhes", product %></p></td>
	  <% if params[:page] %>
	  	<td><p class="btn btn-default"><%= link_to "Adicionar a Venda", add_path(product, params[:page]) %></p></td>
	  <% else %>
	  	<td><p class="btn btn-default"><%= link_to "Adicionar a Venda", add_path(product, "1") %></p></td>
	  <% end %>
	  <% if session[:cart] %>
	  	<% cart = session[:cart]%>
	 	<td><%=  cart["#{product.id}"] %></td>
	  <% else %>
	  	<td></td>
		<% end %>
		 
    
	</tr>
  <% end %>
</tbody>
</table>
<div class="text-center">
  <%= will_paginate @products, :previous_label => 'Anterior', :next_label => 'Próximo', renderer: BootstrapPagination::Rails %>
</div>
</div>


</div>

<% else %>
  <p>Nenhum resultado com os parâmetros <%= params[:search] %></p>
  <%= link_to 'Adicionar Novo Produto', new_product_path, class: "btn btn-link btn-sm" %><br>
  <%= link_to 'Ver estoque completo', products_path, class: "btn btn-link btn-sm" %>
<% end %>

app/views/products/new.html.erb
<h1 class="text-center"><%= t('products.new.title') %></h1>

<%= render 'form' %>

app/views/products/oldindex.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
<div class="panel-heading"><h1 class="text-center">Estoque</h1></div>

<div class="panel-body">
<table class="table table-hover table-bordered text-center">
	<thead>
	  <tr>
	  	<th class="text-center">Referência</th>
	    <th class="text-center">Marca</th>
	    <th class="text-center">Tamanho</th>
	    <th class="text-center">Gênero</th>
	    <th class="text-center">Tipo</th>
	    <th class="text-center">Preço</th>
	    <th colspan="3"></th>
	  </tr>
    </thead>
 <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.reference %></td>
      <td><%= product.brand %></td>
      <td><%= product.size %></td>
      <td><%= product.gender %></td>
      <td><%= product.product_type %></td>
      <td>R$ <%= product.price %></td>
      <td><p class="btn btn-default"><%= link_to "Exibir", product %></p></td>
    </tr>
  <% end %>
</tbody>
</table>
</div>

<div class="row">
  <div class="col-lg-6">
  <%= link_to 'Adicionar Novo Produto', new_product_path, class: "btn btn-link btn-sm" %><br><br>
  <%= link_to "Busca Avançada", new_search_path, class: "btn btn-link btn-sm" %>
  </div>
</div>

</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% if @product.present? %>
<div class="panel panel-default">
  <div class="panel-heading"><h1 class="text-center">Detalhes do Produto</h1></div>
  <div class="panel-body">
    <p>
      <strong>Marca:</strong>
      <%= @product.brand %>
    </p>

    <p>
      <strong>Tamanho:</strong>
      <%= @product.size %>
    </p>

    <p>
      <strong>Referência:</strong>
      <%= @product.reference %>
    </p>

    <p>
      <strong>Gênero:</strong>
      <%= @product.gender %>
    </p>

    <p>
      <strong>Tipo:</strong>
      <%= @product.product_type %>
    </p>

    <p>
      <strong>Preço de Custo:</strong>
      <%= @product.cost_price %>
    </p>

    <p>
      <strong>Preço:</strong>
      <%= @product.price %>
    </p>

    <p>
      <strong>Quantidade em Estoque:</strong>
      <%= @product.stock_quantity %>
    </p>
  </div>

  <div class="panel-footer">
    <div class="btn"><%= link_to 'Editar Produto', edit_product_path(@product) %></div> |
    <div class="btn"><%= link_to 'Voltar', products_path %></div>
  </div>

</div>

<% else %>
  <p>Nenhum resultado com os parâmetros <%= params[:search] %></p>

<% end %>