config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  get 'cart/index'

  constraints(SubdomainPresent) do
    devise_for :users
    resources :products
    resources :clients
    resources :orders
    resources :attendances
    resources :clients
    resources :searches

    root 'products#index', as: :subdomain_root
    get 'choose', to: 'orders#choose_products'
    get 'clear', to: 'cart#clear'
    get 'add/:id/:page', to: 'cart#add', as: 'add'
    get 'remove/:id', to: 'cart#remove', as: 'remove'
    get 'cart/index', to: 'cart#index', as: 'cart'
  end

  constraints(SubdomainBlank) do
    root 'pages#home'
    resources :accounts, only: [:new, :create]
    get 'pages/home' => 'pages#home'
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Optk", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      

      <ul class="nav navbar-nav navbar-right">
	  <% cartCount = 0 %>
      <% if session[:cart] %>
	  
	  	<% cart = session[:cart] %>
		<% cart.each do |id, quantity| %>
			<% cartCount += quantity %>
		<% end %>
	  
	  <% end %>
	  
      <% if user_signed_in? %>
      	<li><%= link_to "Finalizar Venda", clients_path %></li>
		    <li><%= link_to "Venda Atual (#{cartCount})", cart_index_path %></li>
        <li><%= link_to "Consultar Estoque", products_path %></li>
		    <li><%= link_to "Consultar Clientes", clients_path %></li>
        <li><%= link_to "Relatório de Vendas", orders_path %></li>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete %>
      <% end %>


      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OticaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<div class="container">
	<span class="notice_message">
		<% flash.each do |name, msg| %>
	    	<h4><%= content_tag :div, msg, class: "alert alert-info text-center" %></h4>
	  	<% end %>
  	</span>
  	<script>
  		setTimeout("$('.notice_message').fadeOut('slow')", 5000)
  	</script>

	<%= yield %>
</div>

</body>
</html>